name: Deploy on prod
permissions:
  id-token: write
  contents: read
on:
  push:
    tags:
      - v*
jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: sam build -t template.yaml
      - run: >-
          sam deploy --no-confirm-changeset
          --no-fail-on-empty-changeset
          --stack-name clone-client-prod
          --s3-prefix clone-client-prod
          --resolve-s3
          --capabilities CAPABILITY_NAMED_IAM
          --parameter-overrides
          Stage=prod